configuration:
  width: 450
  height: 450
  luminosity-label: '%1$.1f fb^{-1} at #sqrt{s} = 13 TeV'
  experiment: " CMS"
  extra-label: "Preliminary"
  root: ''
  luminosity: 59741
  luminosity-error: 0.025
  error-fill-style: 3254
  error-fill-color: "#ee556270"
  ratio-fit-error-fill-style: 1001
  ratio-fit-error-fill-color: "#aa556270"
  ratio-fit-line-color: "#0B486B"
  blinded-range-fill-color: "#29556270"
  blinded-range-fill-style: 1001
  yields-table-align: v
  book-keeping-file: 'plots.root'
  yields-table-numerical-precision-yields: 2

files: 
  include: ['files_2018.yml']
  #include: ['files_2018_noreco.yml']

systematics:
  - ttLJbb_xsec:   {type: const, value: 1.055, on: 'hist_TTpowhegttbb.root'}
  - ttLJcc_xsec:   {type: const, value: 1.055, on: 'hist_TTpowhegttcc.root'}
  - ttLJlf_xsec:   {type: const, value: 1.055, on: 'hist_TTpowhegttlf.root'}
  - ttLLbb_xsec:   {type: const, value: 1.055, on: 'hist_TTLLpowhegttbb.root'}
  - ttLLcc_xsec:   {type: const, value: 1.055, on: 'hist_TTLLpowhegttcc.root'}
  - ttLLlf_xsec:   {type: const, value: 1.055, on: 'hist_TTLLpowhegttlf.root'}
  - ttHadbb_xsec:  {type: const, value: 1.055, on: 'hist_TTHadpowhegttbb.root'}
  - ttHadcc_xsec:  {type: const, value: 1.055, on: 'hist_TTHadpowhegttcc.root'}
  - ttHadlf_xsec:  {type: const, value: 1.055, on: 'hist_TTHadpowhegttlf.root'}
  - ttLJbb_xsec2:  {type: const, value: 1.3, on: 'hist_TTpowhegttbb.root'}
  - ttLLbb_xsec2:  {type: const, value: 1.3, on: 'hist_TTLLpowhegttbb.root'}
  - ttHadbb_xsec2: {type: const, value: 1.3, on: 'hist_TTHadpowhegttbb.root'}
  - ttLJcc_xsec2:  {type: const, value: 1.5, on: 'hist_TTpowhegttcc.root'}
  - ttLLcc_xsec2:  {type: const, value: 1.5, on: 'hist_TTLLpowhegttcc.root'}
  - ttHadcc_xsec2: {type: const, value: 1.5, on: 'hist_TTHadpowhegttcc.root'}
  - other_xsec1:   {type: const, value: 1.1, on: 'hist_DYJets.root'}
  - other_xsec2:   {type: const, value: 1.1, on: 'hist_DYJets10to50.root'}
  - other_xsec3:   {type: const, value: 1.1, on: 'hist_W1JetsToLNu.root'}
  - other_xsec4:   {type: const, value: 1.1, on: 'hist_W2JetsToLNu.root'}
  - other_xsec5:   {type: const, value: 1.1, on: 'hist_W3JetsToLNu.root'}
  - other_xsec6:   {type: const, value: 1.1, on: 'hist_W4JetsToLNu.root'}
  - other_xsec7:   {type: const, value: 1.1, on: 'hist_SingleTops.root'}
  - other_xsec8:   {type: const, value: 1.1, on: 'hist_SingleTopt.root'}
  - other_xsec9:   {type: const, value: 1.1, on: 'hist_SingleTbart.root'}
  - other_xsec10:  {type: const, value: 1.1, on: 'hist_SingleToptW.root'}
  - other_xsec11:  {type: const, value: 1.1, on: 'hist_SingleTbartW.root'}
  - other_xsec12:  {type: const, value: 1.1, on: 'hist_WW.root'}
  - other_xsec13:  {type: const, value: 1.1, on: 'hist_WZ.root'}
  - other_xsec14:  {type: const, value: 1.1, on: 'hist_ZZ.root'}
  - other_xsec15:  {type: const, value: 1.1, on: 'hist_ttHTobb.root'}
  - other_xsec16:  {type: const, value: 1.1, on: 'hist_ttHToNonbb.root'}
  - other_xsec17:  {type: const, value: 1.1, on: 'hist_TTWJetsToLNuPSweight.root'}
  - other_xsec18:  {type: const, value: 1.1, on: 'hist_TTWJetsToQQ.root'}
  - other_xsec19:  {type: const, value: 1.1, on: 'hist_TTZToLLNuNu.root'}
  - other_xsec20:  {type: const, value: 1.1, on: 'hist_TTZToQQ.root'}
  - pu
  - muid
  - muiso
  - mutrg
  - elid
  - elreco
  - elzvtx
  - eltrg
  - jecAbsolute
  - jecAbsolute2018
  - jecBBEC1
  - jecBBEC12018
  - jecFlavorQCD
  - jecRelativeBal
  - jecRelativeSample2018
  - jer
  - scale: {type: shape, on: 'hist_TTpowhegttbb.root'}
  - scale: {type: shape, on: 'hist_TTpowhegttcc.root'}
  - scale: {type: shape, on: 'hist_TTpowhegttlf.root'}
  - scale: {type: shape, on: 'hist_TTLLpowhegttbb.root'}
  - scale: {type: shape, on: 'hist_TTLLpowhegttcc.root'}
  - scale: {type: shape, on: 'hist_TTLLpowhegttlf.root'}
  - scale: {type: shape, on: 'hist_TTHadpowhegttbb.root'}
  - scale: {type: shape, on: 'hist_TTHadpowhegttcc.root'}
  - scale: {type: shape, on: 'hist_TTHadpowhegttlf.root'}
  - scale: {type: shape, on: 'hist_STTH1L3BHut.root'}
  - scale: {type: shape, on: 'hist_STTH1L3BHct.root'}
  - scale: {type: shape, on: 'hist_TTTH1L3BHut.root'}
  - scale: {type: shape, on: 'hist_TTTH1L3BHct.root'}
  - ps: {type: shape, on: 'hist_TTpowhegttbb.root'}
  - ps: {type: shape, on: 'hist_TTpowhegttcc.root'}
  - ps: {type: shape, on: 'hist_TTpowhegttlf.root'}
  - ps: {type: shape, on: 'hist_TTLLpowhegttbb.root'}
  - ps: {type: shape, on: 'hist_TTLLpowhegttcc.root'}
  - ps: {type: shape, on: 'hist_TTLLpowhegttlf.root'}
  - ps: {type: shape, on: 'hist_TTHadpowhegttbb.root'}
  - ps: {type: shape, on: 'hist_TTHadpowhegttcc.root'}
  - ps: {type: shape, on: 'hist_TTHadpowhegttlf.root'}
  - ps: {type: shape, on: 'hist_STTH1L3BHut.root'}
  - ps: {type: shape, on: 'hist_STTH1L3BHct.root'}
  - ps: {type: shape, on: 'hist_TTTH1L3BHut.root'}
  - ps: {type: shape, on: 'hist_TTTH1L3BHct.root'}
  - hdamp: {type: shape, on: 'hist_TTpowhegttbb.root'}
  - hdamp: {type: shape, on: 'hist_TTpowhegttcc.root'}
  - hdamp: {type: shape, on: 'hist_TTpowhegttlf.root'}
  - hdamp: {type: shape, on: 'hist_TTLLpowhegttbb.root'}
  - hdamp: {type: shape, on: 'hist_TTLLpowhegttcc.root'}
  - hdamp: {type: shape, on: 'hist_TTLLpowhegttlf.root'}
  - hdamp: {type: shape, on: 'hist_TTHadpowhegttbb.root'}
  - hdamp: {type: shape, on: 'hist_TTHadpowhegttcc.root'}
  - hdamp: {type: shape, on: 'hist_TTHadpowhegttlf.root'}
  - pdf: {type: shape, on: 'hist_TTpowhegttbb.root'}
  - pdf: {type: shape, on: 'hist_TTpowhegttcc.root'}
  - pdf: {type: shape, on: 'hist_TTpowhegttlf.root'}
  - pdf: {type: shape, on: 'hist_TTLLpowhegttbb.root'}
  - pdf: {type: shape, on: 'hist_TTLLpowhegttcc.root'}
  - pdf: {type: shape, on: 'hist_TTLLpowhegttlf.root'}
  - pdf: {type: shape, on: 'hist_TTHadpowhegttbb.root'}
  - pdf: {type: shape, on: 'hist_TTHadpowhegttcc.root'}
  - pdf: {type: shape, on: 'hist_TTHadpowhegttlf.root'}
  - pdf: {type: shape, on: 'hist_STTH1L3BHut.root'}
  - pdf: {type: shape, on: 'hist_STTH1L3BHct.root'}
  - pdf: {type: shape, on: 'hist_TTTH1L3BHut.root'}
  - pdf: {type: shape, on: 'hist_TTTH1L3BHct.root'}
  - TuneCP5: {type: shape, on: 'hist_TTpowhegttbb.root'}
  - TuneCP5: {type: shape, on: 'hist_TTpowhegttcc.root'}
  - TuneCP5: {type: shape, on: 'hist_TTpowhegttlf.root'}
  - TuneCP5: {type: shape, on: 'hist_TTLLpowhegttbb.root'}
  - TuneCP5: {type: shape, on: 'hist_TTLLpowhegttcc.root'}
  - TuneCP5: {type: shape, on: 'hist_TTLLpowhegttlf.root'}
  - TuneCP5: {type: shape, on: 'hist_TTHadpowhegttbb.root'}
  - TuneCP5: {type: shape, on: 'hist_TTHadpowhegttcc.root'}
  - TuneCP5: {type: shape, on: 'hist_TTHadpowhegttlf.root'}
  - lf
  - hf
  - lfstat1
  - lfstat2
  - hfstat1
  - hfstat2
  - cferr1
  - cferr2

plots:
#  include: ['histos_control.yml']
#  include: ['histos_control_qcd.yml']
#  include: ['histos_nopuSF.yml']
#  include: ['histos_nobSF.yml']
#  include: ['histos_stfcnc.yml']
#  include: ['histos_stfcnc_qcd.yml']
#  include: ['histos_stfcnc_b4j4.yml']
#  include: ['histos_ttfcnc.yml']
#  include: ['histos_ttfcnc_b4j4.yml']
#  include: ['histos_ttbkg.yml']
#  include: ['histos_ttbkg_b4j4.yml']
#  include: ['histos_input_st.yml']
#  include: ['histos_input_st_qcd.yml']
#  include: ['histos_input_st_b4j4.yml']
#  include: ['histos_input_tt.yml']
#  include: ['histos_input_tt_b4j4.yml']
  include: ['histos_dnn.yml']
#  include: ['histos_unc.yml']
#  include: ['histos_yield.yml']
#  include: ['histos_ttfcnc_qcd.yml']
#  include: ['histos_ttbkg_qcd.yml']

legend:
  position: [0.18, 0.70, 0.96, 0.88]
#  position: [0.18, 0.73, 0.92, 0.89] #For old dnn
  columns: 5

groups:
  include: ['groups.yml']

