#####S8#####
'h_jet0pt_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_jet0eta_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_jet0m_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_jet0csv_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_jet1pt_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_jet1eta_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_jet1m_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_jet1csv_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_jet2pt_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_jet2eta_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_jet2m_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_jet2csv_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_jet3pt_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_jet3eta_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_jet3m_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_jet3csv_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_jet12pt_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_jet12eta_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_jet12deta_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_jet12dphi_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_jet12dR_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_jet12m_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_jet23pt_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_jet23eta_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_jet23deta_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_jet23dphi_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_jet23dR_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_jet23m_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_jet31pt_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_jet31eta_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_jet31deta_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_jet31dphi_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_jet31dR_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_jet31m_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_lepTpt_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_lepTdphi_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_lepTm_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_hadTpt_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_hadTeta_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_hadT12_3deta_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_hadT23_1deta_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_hadT31_2deta_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_hadT12_3dphi_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_hadT23_1dphi_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_hadT31_2dphi_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_hadT12_3dR_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_hadT23_1dR_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_hadT31_2dR_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_hadTm_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_jet0lepdR_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_jet1lepdR_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_jet2lepdR_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_jet3lepdR_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_jet01dR_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_jet02dR_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_jet03dR_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_jet12_lepdR_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_jet23_lepdR_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_jet31_lepdR_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_jet12_0dR_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_jet23_0dR_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_jet31_0dR_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_lepTjet12dphi_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_lepTjet23dphi_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_lepTjet31dphi_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_hadT_jet0dR_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}
