'h_FCNHkinHMass_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_FCNHkinDR_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_FCNHkinLepTopM_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_FCNHkinLepTopPt_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_FCNHkinHb2CSV_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_FCNHkinHb2CSVfull_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  x-axis-range: [0.4,1.0]
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}

'h_FCNHkinScore_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  save-extensions: ['pdf']
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}
