#Ch2
'h_FCNHkinHMass_Ch2_S3':
  x-axis: "m_{b#bar b} (GeV)"
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f GeV"
  save-extensions: ['pdf']
  ratio-y-axis-auto-range: true
  labels:
    #- {text: 'b3j3', position: [0.789, 0.806], size: 18}
    - {text: 'b3j3', position: [0.2, 0.832], size: 18, font: 44}
