'h_FCNHkinHb2CSVfull_Ch2_S8':
  y-axis: "Events"
  y-axis-format: "%1% / %2$.2f"
  x-axis-range: [0.4,1.0]
  save-extensions: ['pdf']
  ratio-y-axis-auto-range: true
  labels:
    - {text: 'b4j4', position: [0.789, 0.806], size: 18}
