#!/usr/bin/python
from ROOT import *
import os, sys
gROOT.SetBatch(True)

test = os.listdir("/home/minerva1993/fcnc/analysis_2017/fullAna/temp")
for item in test:
  if item.endswith(".root"):
    os.remove(os.path.join("/home/minerva1993/fcnc/analysis_2017/fullAna/temp", item))

def runAna(file_path, name):
  print 'processing ' + file_path
  chain = TChain("fcncLepJets/tree","events")
  chain.Add(file_path)
  chain.SetProof();
  chain.Process("MyAnalysis.C+", name)
  #print chain.GetCurrentFile().GetName()

  f = TFile.Open(file_path, "READ")

  ## save Event Summary histogram ##
  out = TFile("temp/hist_" + name + ".root", "update")
  hevt = f.Get("fcncLepJets/EventInfo")
  hevt.Write()
  out.Write()
  out.Close()

p = TProof.Open("", "workers=8")

