import os
#from ROOT import *
from ROOT import TStyle, TF1, TFile, TCanvas, gDirectory, TTree, TH1D, TH1F, THStack, TLegend, gROOT
import ROOT
from style import *

scaleHct = 0.02
scaleHut = 0.003

c1 = TCanvas( 'c1', 'c1', 450, 450 ) 

hct_gendR = TH1D('hct_gendR','#Delta R of gen b jets (Hct)', 30, 0, 4)
hut_gendR = TH1D('hut_gendR','#Delta R of gen b jets (Hut)', 30, 0, 4)
hct_recodR = TH1D('hct_recodR','#Delta R of reco b jets (Hct)', 30, 0, 4)
hut_recodR = TH1D('hut_recodR','#Delta R of reco b jets (Hut)', 30, 0, 4)

hct_genHm = TH1D('hct_genHm','Mass of gen H (Hct)', 30, 0, 250)
hut_genHm = TH1D('hut_genHm','Mass of gen H (Hut)', 30, 0, 250)
hct_recoHm = TH1D('hct_recoHm','Mass of reco H (Hct)', 30, 0, 250)
hut_recoHm = TH1D('hut_recoHm','Mass of reco H (Hut)', 30, 0, 250)

hct_matchHm = TH1D('hct_matchHm','Mass of gen matched H (Hct)', 30, 0, 250)
hut_matchHm = TH1D('hut_matchHm','Mass of gen matched H (Hut)', 30, 0, 250)

tch = TFile.Open('/home/minerva1993/HEPToolsFCNC/analysis_2017/fullAna/hist_STTH1L3BHct.root')
tuh = TFile.Open('/home/minerva1993/HEPToolsFCNC/analysis_2017/fullAna/hist_STTH1L3BHut.root ')

label = TPaveText()
label.SetX1NDC(gStyle.GetPadLeftMargin())
label.SetY1NDC(1.0-gStyle.GetPadTopMargin())
label.SetX2NDC(1.0-gStyle.GetPadRightMargin()+0.03)
label.SetY2NDC(1.0)
label.SetTextFont(62)
label.AddText("Work in Progress        CMS, 41.5 fb^{-1} at #sqrt{s} = 13 TeV")
label.SetFillStyle(0)
label.SetBorderSize(0)
label.SetTextSize(0.035)
label.SetTextAlign(32)

##all histos with event selection!
###########################################################
##j>=3, b >=2
tch_gendR_ch0 = tch.Get('h_genDR_Ch0_S6_STTH1L3BHct')
tuh_gendR_ch0 = tuh.Get('h_genDR_Ch0_S6_STTH1L3BHut')
tch_gendR_ch1 = tch.Get('h_genDR_Ch1_S6_STTH1L3BHct')
tuh_gendR_ch1 = tuh.Get('h_genDR_Ch1_S6_STTH1L3BHut')

hct_gendR = tch_gendR_ch0.Clone('hct_gendR')
hct_gendR.Add(tch_gendR_ch1,1.0)
hct_gendR.Scale(scaleHct)
hct_gendR.SetTitle('')
hct_gendR.GetYaxis().SetTitle("Events")

c1.cd()
hct_gendR.Draw('HIST')
label.Draw("same")
#c1.Print('h_hct_gendR.pdf')

hut_gendR = tuh_gendR_ch0.Clone('hut_gendR')
hut_gendR.Add(tuh_gendR_ch1,1.0)
hut_gendR.Scale(scaleHut)
hut_gendR.SetTitle('')
hut_gendR.GetYaxis().SetTitle("Events")

c1.cd()
c1.Clear()
hut_gendR.Draw('HIST')
label.Draw("same")
#c1.Print('h_hut_gendR.pdf')

###########################################################

tch_recodR_ch0 = tch.Get('h_FCNHkinDR_Ch0_S6_STTH1L3BHct')
tuh_recodR_ch0 = tuh.Get('h_FCNHkinDR_Ch0_S6_STTH1L3BHut')
tch_recodR_ch1 = tch.Get('h_FCNHkinDR_Ch1_S6_STTH1L3BHct')
tuh_recodR_ch1 = tuh.Get('h_FCNHkinDR_Ch1_S6_STTH1L3BHut')

hct_recodR = tch_recodR_ch0.Clone('hct_recodR')
hct_recodR.Add(tch_recodR_ch1,1.0)
hct_recodR.Scale(scaleHct)
hct_recodR.SetTitle('')
hct_recodR.GetYaxis().SetTitle("Events")

c1.cd()
c1.Clear()
hct_recodR.Draw('HIST')
label.Draw("same")
#c1.Print('h_hct_recodR.pdf')

hut_recodR = tuh_recodR_ch0.Clone('hut_recodR')
hut_recodR.Add(tuh_recodR_ch1,1.0)
hut_recodR.Scale(scaleHut)
hut_recodR.SetTitle('')
hut_recodR.GetYaxis().SetTitle("Events")

c1.cd()
c1.Clear()
hut_recodR.Draw('HIST')
label.Draw("same")
#c1.Print('h_hut_recodR.pdf')

###########################################################

c1.cd()
c1.Clear()
hct_gendR.SetLineColor(2)
hct_recodR.SetLineColor(4)
hct_recodR.SetStats(0)
hct_recodR.SetTitle('')
hct_recodR.DrawNormalized('HIST')
hct_gendR.DrawNormalized('SAME HIST')
l1 = TLegend(0.68, 0.76, 0.85, 0.86)
l1.AddEntry(hct_gendR, 'Gen', 'l')
l1.AddEntry(hct_recodR, 'Reco', 'l')
l1.Draw('SAME')
label.Draw("same")
#c1.Print('h_hct_comp_dR_nor.pdf')

c1.cd()
c1.Clear()
hct_recodR.SetTitle('')
hct_recodR.Draw('HIST')
hct_gendR.Draw('SAME HIST')
l1.Clear()
l1.AddEntry(hct_gendR, 'Gen', 'l')
l1.AddEntry(hct_recodR, 'Reco', 'l')
l1.Draw('SAME')
label.Draw("same")
#c1.Print('h_hct_comp_dR.pdf')

c1.cd()
c1.Clear()
hut_gendR.SetLineColor(2)
hut_recodR.SetLineColor(4)
hut_recodR.SetStats(0)
hut_recodR.SetTitle('')
hut_recodR.DrawNormalized('HIST')
hut_gendR.DrawNormalized('SAME HIST')
l1.Clear()
l1.AddEntry(hut_gendR, 'Gen', 'l')
l1.AddEntry(hut_recodR, 'Reco', 'l')
l1.Draw('SAME')
label.Draw("same")
#c1.Print('h_hut_comp_dR_nor.pdf')

c1.cd()
c1.Clear()
hut_recodR.SetTitle('')
hut_recodR.Draw('HIST')
hut_gendR.Draw('SAME HIST')
l1.Clear()
l1.AddEntry(hut_gendR, 'Gen', 'l')
l1.AddEntry(hut_recodR, 'Reco', 'l')
l1.Draw('SAME')
label.Draw("same")
#c1.Print('h_hut_comp_dR.pdf')

###########################################################
###########################################################

tch_genHm_ch0 = tch.Get('h_genHm_Ch0_S6_STTH1L3BHct')
tuh_genHm_ch0 = tuh.Get('h_genHm_Ch0_S6_STTH1L3BHut')
tch_genHm_ch1 = tch.Get('h_genHm_Ch1_S6_STTH1L3BHct')
tuh_genHm_ch1 = tuh.Get('h_genHm_Ch1_S6_STTH1L3BHut')

hct_genHm = tch_genHm_ch0.Clone('hct_genHm')
hct_genHm.Add(tch_genHm_ch1,1.0)
hct_genHm.Scale(scaleHct)
hct_genHm.SetTitle('')
hct_genHm.GetXaxis().SetRangeUser(0,250)
hct_genHm.GetYaxis().SetTitle("Events")

c1.cd()
hct_genHm.Draw('HIST')
label.Draw("same")
#c1.Print('h_hct_genHm.pdf')

hut_genHm = tuh_genHm_ch0.Clone('hut_genHm')
hut_genHm.Add(tuh_genHm_ch1,1.0)
hut_genHm.Scale(scaleHut)
hut_genHm.SetTitle('')
hut_genHm.GetXaxis().SetRangeUser(0,250)
hut_genHm.GetYaxis().SetTitle("Events")

c1.cd()
c1.Clear()
hut_genHm.Draw('HIST')
label.Draw("same")
#c1.Print('h_hut_genHm.pdf')

###########################################################

tch_recoHm_ch0 = tch.Get('h_FCNHkinHMass_Ch0_S6_STTH1L3BHct')
tuh_recoHm_ch0 = tuh.Get('h_FCNHkinHMass_Ch0_S6_STTH1L3BHut')
tch_recoHm_ch1 = tch.Get('h_FCNHkinHMass_Ch1_S6_STTH1L3BHct')
tuh_recoHm_ch1 = tuh.Get('h_FCNHkinHMass_Ch1_S6_STTH1L3BHut')

hct_recoHm = tch_recoHm_ch0.Clone('hct_recoHm')
hct_recoHm.Add(tch_recoHm_ch1,1.0)
hct_recoHm.Scale(scaleHct)
hct_recoHm.SetTitle('')
hct_recoHm.GetXaxis().SetRangeUser(0,250)
hct_recoHm.GetYaxis().SetTitle("Events")

c1.cd()
c1.Clear()
hct_recoHm.Draw('HIST')
label.Draw("same")
#c1.Print('h_hct_recoHm.pdf')

hut_recoHm = tuh_recoHm_ch0.Clone('hut_recoHm')
hut_recoHm.Add(tuh_recoHm_ch1,1.0)
hut_recoHm.Scale(scaleHut)
hut_recoHm.SetTitle('')
hut_recoHm.GetXaxis().SetRangeUser(0,250)
hut_recoHm.GetYaxis().SetTitle("Events")

c1.cd()
c1.Clear()
hut_recoHm.Draw('HIST')
label.Draw("same")
#c1.Print('h_hut_recoHm.pdf')

###########################################################

c1.cd()
c1.Clear()
hct_genHm.SetLineColor(2)
hct_recoHm.SetLineColor(4)
hct_genHm.SetStats(0)
hct_genHm.SetTitle('')
hct_genHm.GetXaxis().SetRangeUser(0,250)
hct_genHm.DrawNormalized('HIST')
hct_recoHm.DrawNormalized('SAME HIST')
l1.Clear()
l1.AddEntry(hct_genHm, 'Gen', 'l')
l1.AddEntry(hct_recoHm, 'Reco', 'l')
l1.Draw('SAME')
label.Draw("same")
#c1.Print('h_hct_comp_Hm_nor.pdf')

c1.cd()
c1.Clear()
hct_genHm.SetTitle('')
hct_genHm.GetXaxis().SetRangeUser(0,250)
hct_genHm.Draw('HIST')
hct_recoHm.Draw('SAME HIST')
l1.Clear()
l1.AddEntry(hct_genHm, 'Gen', 'l')
l1.AddEntry(hct_recoHm, 'Reco', 'l')
l1.Draw('SAME')
label.Draw("same")
#c1.Print('h_hct_comp_Hm.pdf')

c1.cd()
c1.Clear()
hut_genHm.SetLineColor(2)
hut_recoHm.SetLineColor(4)
hut_genHm.SetStats(0)
hut_genHm.SetTitle('')
hut_genHm.GetXaxis().SetRangeUser(0,250)
hut_genHm.DrawNormalized('HIST')
hut_recoHm.DrawNormalized('SAME HIST')
l1.Clear()
l1.AddEntry(hut_genHm, 'Gen', 'l')
l1.AddEntry(hut_recoHm, 'Reco', 'l')
l1.Draw('SAME')
label.Draw("same")
#c1.Print('h_hut_comp_Hm_nor.pdf')

c1.cd()
c1.Clear()
hut_genHm.SetTitle('')
hut_genHm.GetXaxis().SetRangeUser(0,250)
hut_genHm.Draw('HIST')
hut_recoHm.Draw('SAME HIST')
l1.Clear()
l1.AddEntry(hut_genHm, 'Gen', 'l')
l1.AddEntry(hut_recoHm, 'Reco', 'l')
l1.Draw('SAME')
label.Draw("same")
#c1.Print('h_hut_comp_Hm.pdf')

###########################################################
###########################################################

tch_matchHm_ch0 = tch.Get('h_matchHm_Ch0_S6_STTH1L3BHct')
tuh_matchHm_ch0 = tuh.Get('h_matchHm_Ch0_S6_STTH1L3BHut')
tch_matchHm_ch1 = tch.Get('h_matchHm_Ch1_S6_STTH1L3BHct')
tuh_matchHm_ch1 = tuh.Get('h_matchHm_Ch1_S6_STTH1L3BHut')

hct_matchHm = tch_matchHm_ch0.Clone('hct_matchHm')
hct_matchHm.Add(tch_matchHm_ch1,1.0)
hct_matchHm.Scale(scaleHct)
hct_matchHm.SetTitle('')
hct_matchHm.GetXaxis().SetRangeUser(0,250)
hct_matchHm.GetYaxis().SetTitle("Events")

c1.cd()
c1.Clear()
hct_matchHm.Draw('HIST')
label.Draw("same")
#c1.Print('h_hct_matchHm.pdf')

hut_matchHm = tuh_matchHm_ch0.Clone('hut_matchHm')
hut_matchHm.Add(tuh_matchHm_ch1,1.0)
hut_matchHm.Scale(scaleHut)
hut_matchHm.SetTitle('')
hut_matchHm.GetXaxis().SetRangeUser(0,250)
hut_matchHm.GetYaxis().SetTitle("Events")

c1.cd()
c1.Clear()
hut_matchHm.Draw('HIST')
label.Draw("same")
#c1.Print('h_hut_matchHm.pdf')

###########################################################

c1.cd()
c1.Clear()
hct_matchHm.SetLineColor(2)
hct_matchHm.SetLineStyle(7)
hct_recoHm.SetLineColor(4)
hct_matchHm.SetStats(0)
hct_matchHm.SetTitle('')
hct_matchHm.GetXaxis().SetRangeUser(0,250)
hct_matchHm.DrawNormalized('HIST')
hct_recoHm.DrawNormalized('SAME HIST')
l2 = TLegend(0.68, 0.76, 0.85, 0.86)
l2.AddEntry(hct_matchHm, 'matched', 'l')
l2.AddEntry(hct_recoHm, 'Reco', 'l')
l2.Draw('SAME')
label.Draw("same")
#c1.Print('h_hct_reco_match_Hm_nor.pdf')

c1.cd()
c1.Clear()
hct_recoHm.Draw('HIST')
hct_recoHm.SetStats(0)
hct_matchHm.Draw('SAME HIST')
l2.Clear()
l2.AddEntry(hct_matchHm, 'matched', 'l')
l2.AddEntry(hct_recoHm, 'Reco', 'l')
l2.Draw('SAME')
label.Draw("same")
c1.Print('h_hct_reco_match_Hm.pdf')

c1.cd()
c1.Clear()
hut_matchHm.SetLineColor(2)
hut_matchHm.SetLineStyle(7)
hut_recoHm.SetLineColor(4)
hut_matchHm.SetStats(0)
hut_matchHm.SetTitle('')
hut_matchHm.GetXaxis().SetRangeUser(0,250)
hut_matchHm.DrawNormalized('HIST')
hut_recoHm.DrawNormalized('SAME HIST')
l2.Clear()
l2.AddEntry(hut_matchHm, 'matched', 'l')
l2.AddEntry(hut_recoHm, 'Reco', 'l')
l2.Draw('SAME')
label.Draw("same")
#c1.Print('h_hut_reco_match_Hm_nor.pdf')

c1.cd()
c1.Clear()
hut_recoHm.Draw('HIST')
hut_recoHm.SetStats(0)
hut_matchHm.Draw('SAME HIST')
l2.Clear()
l2.AddEntry(hut_matchHm, 'matched', 'l')
l2.AddEntry(hut_recoHm, 'Reco', 'l')
l2.Draw('SAME')
label.Draw("same")
c1.Print('h_hut_reco_match_Hm.pdf')

############################3

tch_matchdR_ch0 = tch.Get('h_matchDR_Ch0_S6_STTH1L3BHct')
tuh_matchdR_ch0 = tuh.Get('h_matchDR_Ch0_S6_STTH1L3BHut')
tch_matchdR_ch1 = tch.Get('h_matchDR_Ch1_S6_STTH1L3BHct')
tuh_matchdR_ch1 = tuh.Get('h_matchDR_Ch1_S6_STTH1L3BHut')

hct_matchdR = tch_matchdR_ch0.Clone('hct_matchdR')
hct_matchdR.Add(tch_matchdR_ch1,1.0)
hct_matchdR.Scale(scaleHct)
hct_matchdR.SetTitle('')
hct_matchdR.GetYaxis().SetTitle("Events")

c1.cd()
c1.Clear()
hct_recodR.Draw('HIST')
label.Draw("same")
#c1.Print('h_hct_matchdR.pdf')

hut_matchdR = tuh_recodR_ch0.Clone('hut_matchdR')
hut_matchdR.Add(tuh_matchdR_ch1,1.0)
hut_matchdR.Scale(scaleHut)
hut_matchdR.SetTitle('')
hut_matchdR.GetYaxis().SetTitle("Events")

c1.cd()
c1.Clear()
hut_recodR.Draw('HIST')
label.Draw("same")
#c1.Print('h_hut_matchdR.pdf')

#########################

c1.cd()
c1.Clear()
hct_recodR.SetLineColor(4)
hct_matchdR.SetLineColor(2)
hct_matchdR.SetLineStyle(7)
hct_recodR.Draw('HIST')
hct_recodR.SetStats(0)
hct_matchdR.Draw('SAME HIST')
l2.Clear()
l2.AddEntry(hct_matchdR, 'matched', 'l')
l2.AddEntry(hct_recodR, 'Reco', 'l')
l2.Draw('SAME')
label.Draw("same")
c1.Print('h_hct_reco_match_DR.pdf')

c1.cd()
c1.Clear()
hut_recodR.SetLineColor(4)
hut_matchdR.SetLineColor(2)
hut_matchdR.SetLineStyle(7)
hut_recodR.Draw('HIST')
hut_recodR.SetStats(0)
hut_matchdR.Draw('SAME HIST')
l2.Clear()
l2.AddEntry(hut_matchdR, 'matched', 'l')
l2.AddEntry(hut_recodR, 'Reco', 'l')
l2.Draw('SAME')
label.Draw("same")
c1.Print('h_hut_reco_match_DR.pdf')
