from ROOT import TStyle, TF1, TFile, TCanvas, gDirectory, TTree, TH1F, TH2F, THStack, TLegend, gROOT, TPad, TColor, TPaveText, gStyle
import ROOT
import os

tmva_version = 'v7'

ch = 'Hct1'
#ch = 'Hut1'

bdt_data = TH1F('bdt_data',ch+' BDT Score',20,-0.3,0.3)
bdt_sig = TH1F('bdt_sig','',20,-0.3,0.3)

keras_data = TH1F('keras_data',ch+' Keras Score',20,0,1)
keras_sig = TH1F('keras_sig','',20,0,1)
keras_bkg = TH1F('keras_bkg','',20,0,1)

hs_bdt_bkg = THStack()
hs_keras_bkg = THStack()

shape_file = TFile.Open('/home/minerva1993/fcnc/analysis_jw/limitSetting/limitSettingInput/shape_'+tmva_version+'_'+ch+'.root')

########################################
bdt_ttbb = shape_file.Get('bdt_ttbb')
bdt_ttbj = shape_file.Get('bdt_ttbj')
bdt_ttcc = shape_file.Get('bdt_ttcc')
bdt_ttLF = shape_file.Get('bdt_ttLF')
bdt_singletop = shape_file.Get('bdt_singletop')
bdt_others = shape_file.Get('bdt_others')
bdt_data = shape_file.Get('bdt_data_obs')
bdt_sig = shape_file.Get('bdt_sig')

bdt_ttbb.SetFillColor(ROOT.kRed+4)
bdt_ttbj.SetFillColor(ROOT.kRed+3)
bdt_ttcc.SetFillColor(ROOT.kRed+2)
bdt_ttLF.SetFillColor(ROOT.kRed)
bdt_singletop.SetFillColor(6)
bdt_others.SetFillColor(ROOT.kYellow)
bdt_ttbb.SetLineColor(1)
bdt_ttbj.SetLineColor(1)
bdt_ttcc.SetLineColor(1)
bdt_ttLF.SetLineColor(1)
bdt_singletop.SetLineColor(1)
bdt_others.SetLineColor(1)

hs_bdt_bkg.Add(bdt_ttbb)
hs_bdt_bkg.Add(bdt_ttbj)
hs_bdt_bkg.Add(bdt_ttcc)
hs_bdt_bkg.Add(bdt_ttLF)
hs_bdt_bkg.Add(bdt_singletop)
hs_bdt_bkg.Add(bdt_others)

bdt_sig.Scale(bdt_data.Integral()/bdt_sig.Integral())
bdt_sig.SetLineColor(8)
bdt_sig.SetLineWidth(3)

########################################
keras_ttbb = shape_file.Get('keras_ttbb')
keras_ttbj = shape_file.Get('keras_ttbj')
keras_ttcc = shape_file.Get('keras_ttcc')
keras_ttLF = shape_file.Get('keras_ttLF')
keras_singletop = shape_file.Get('keras_singletop')
keras_others = shape_file.Get('keras_others')
keras_data = shape_file.Get('keras_data_obs')
keras_sig = shape_file.Get('keras_sig')

keras_ttbb.SetFillColor(ROOT.kRed+4)
keras_ttbj.SetFillColor(ROOT.kRed+3)
keras_ttcc.SetFillColor(ROOT.kRed+2)
keras_ttLF.SetFillColor(ROOT.kRed)
keras_singletop.SetFillColor(6)
keras_others.SetFillColor(ROOT.kYellow)
keras_ttbb.SetLineColor(1)
keras_ttbj.SetLineColor(1)
keras_ttcc.SetLineColor(1)
keras_ttLF.SetLineColor(1)
keras_singletop.SetLineColor(1)
keras_others.SetLineColor(1)

hs_keras_bkg.Add(keras_ttbb)
hs_keras_bkg.Add(keras_ttbj)
hs_keras_bkg.Add(keras_ttcc)
hs_keras_bkg.Add(keras_ttLF)
hs_keras_bkg.Add(keras_singletop)
hs_keras_bkg.Add(keras_others)

keras_sig.Scale(keras_data.Integral()/keras_sig.Integral())
keras_sig.SetLineColor(8)
keras_sig.SetLineWidth(3)

########################################
c1 = TCanvas( 'c1', 'c1', 450, 450 )
pad1 = TPad("pad1", "pad1", 0.0, 0.3, 1, 1.0)
pad1.SetBottomMargin(0.02)
pad1.SetLeftMargin(0.12)
pad1.Draw()
c1.cd()  # returns to main canvas before defining pad2
pad2 = TPad("pad2", "pad2", 0.0, 0.0, 1, 0.28)
pad2.SetBottomMargin(0.3)
pad2.SetTopMargin(0.02)
pad2.SetLeftMargin(0.12)
pad2.SetGridx()
pad2.SetGridy()
pad2.Draw()

l = TLegend(0.5,0.70,0.89,0.89)
l.SetNColumns(3)
l.SetTextFont(62)
l.SetTextSize(0.05)
l.SetLineColor(0)
l.SetFillColor(0)
l.AddEntry(bdt_ttbb, 'ttbb', 'F')
l.AddEntry(bdt_ttbj, 'ttbj', 'F')
l.AddEntry(bdt_ttcc, 'ttcc', 'F')
l.AddEntry(bdt_ttLF, 'ttLF', 'F')
l.AddEntry(bdt_singletop, 'ST', 'F')
l.AddEntry(bdt_others, 'W+j/DY', 'F')
l.AddEntry(0, "", "")
l.AddEntry(bdt_sig, "Sig", "F")
l.AddEntry(bdt_data, 'Data', 'P')

label = TPaveText()
label.SetX1NDC(gStyle.GetPadLeftMargin())
label.SetY1NDC(1.0-gStyle.GetPadTopMargin())
label.SetX2NDC(1.0-gStyle.GetPadRightMargin()+0.03)
label.SetY2NDC(1.0)
label.SetTextFont(62)
label.AddText("Work in Progress        CMS, 35.9 fb^{-1} at #sqrt{s} = 13 TeV")
label.SetFillStyle(0)
label.SetBorderSize(0)
label.SetTextSize(0.05)
label.SetTextAlign(32)

##########################################
pad1.cd()
bdt_data.SetTitle("")
bdt_data.SetMarkerStyle(20)
bdt_data.SetMarkerSize(0.5)
bdt_data.SetStats(0)
bdt_data.SetMaximum(bdt_data.GetMaximum() * 1.35)
bdt_data.GetYaxis().SetTitle("Events")
bdt_data.GetYaxis().SetTitleOffset(1.2)
bdt_data.GetYaxis().SetTitleSize(0.045)
bdt_data.GetXaxis().SetLabelSize(0)#
bdt_data.GetXaxis().SetTitleOffset(5.0)
bdt_data.Draw('P')
hs_bdt_bkg.Draw('HIST SAME E')
bdt_sig.SetFillStyle(0)
bdt_sig.Draw('HIST SAME E')
bdt_data.Draw("P axis same")
l.Draw("same")
label.Draw("same")
pad2.cd()
r_bdt_data = bdt_data.Clone("r_bdt_data")
r_bdt_data.SetLineColor(1)
r_bdt_data.SetMarkerStyle(20)
r_bdt_data.SetMarkerSize(0.5)
r_bdt_data.SetTitle("")
r_bdt_data.Divide(hs_bdt_bkg.GetStack().Last())
y = r_bdt_data.GetYaxis()
y.SetTitle("Data/MC")
y.SetNdivisions(505)
y.SetTitleSize(0.11)
y.SetRangeUser(0.6,1.4)
y.SetTitleOffset(0.35)
y.SetLabelSize(0.1)
x = r_bdt_data.GetXaxis()
x.SetTitleSize(0.11)
x.SetTitleOffset(1.0)
x.SetLabelSize(0.1)
r_bdt_data.Draw("EP")
c1.Print('histo_'+tmva_version+'_'+ch+'_bdt.pdf')

################################################
pad1.Clear()
pad2.Clear()
pad1.cd()
keras_data.SetTitle("")
keras_data.SetMarkerStyle(20)
keras_data.SetMarkerSize(0.5)
keras_data.SetStats(0)
keras_data.SetMaximum(keras_data.GetMaximum() * 1.35)
keras_data.GetYaxis().SetTitle("Events")
keras_data.GetYaxis().SetTitleOffset(1.2)
keras_data.GetYaxis().SetTitleSize(0.045)
keras_data.GetXaxis().SetLabelSize(0)#
keras_data.GetXaxis().SetTitleOffset(5.0)
keras_data.Draw('P')
hs_keras_bkg.Draw('HIST SAME E')
keras_sig.SetFillStyle(0)
keras_sig.Draw('HIST SAME E')
keras_data.Draw("P axis same")
l.Draw("same")
label.Draw("same")
pad2.cd()
r_keras_data = keras_data.Clone("r_keras_data")
r_keras_data.SetLineColor(1)
r_keras_data.SetMarkerStyle(20)
r_keras_data.SetMarkerSize(0.5)
r_keras_data.SetTitle("")
r_keras_data.Divide(hs_keras_bkg.GetStack().Last())
y = r_keras_data.GetYaxis()
y.SetTitle("Data/MC")
y.SetNdivisions(505)
y.SetTitleSize(0.11)
y.SetRangeUser(0.6,1.4)
y.SetTitleOffset(0.35)
y.SetLabelSize(0.1)
x = r_keras_data.GetXaxis()
x.SetTitleSize(0.11)
x.SetTitleOffset(1.0)
x.SetLabelSize(0.1)
r_keras_data.Draw("EP")
c1.Print('histo_'+tmva_version+'_'+ch+'_keras.pdf')
