import os
#from ROOT import *
from ROOT import TStyle, TF1, TFile, TCanvas, gDirectory, TTree, TH1D, TH1F, THStack, TLegend, gROOT
import ROOT
from style import *

c1 = TCanvas( 'c1', 'c1', 500, 500 ) 

mu = TFile.Open('~/fcnc/analysis_jw/fullAna/offline_selection/hist_DataSingleMu.root')
el = TFile.Open('~/fcnc/analysis_jw/fullAna/offline_selection/hist_DataSingleEG.root')
tch = TFile.Open('~/fcnc/analysis_jw/fullAna/offline_selection/hist_Top_Hct.root')
tuh = TFile.Open('~/fcnc/analysis_jw/fullAna/offline_selection/hist_Top_Hut.root')
atch = TFile.Open('~/fcnc/analysis_jw/fullAna/offline_selection/hist_AntiTop_Hct.root')
atuh = TFile.Open('~/fcnc/analysis_jw/fullAna/offline_selection/hist_AntiTop_Hut.root')

label = TPaveText()
label.SetX1NDC(gStyle.GetPadLeftMargin()+0.32)
label.SetY1NDC(1.0-gStyle.GetPadTopMargin()-0.02)
label.SetX2NDC(1.0-gStyle.GetPadRightMargin()+0.03)
label.SetY2NDC(1.0)
label.SetTextFont(62)
label.AddText("Work in progress, #sqrt{s} = 13 TeV")
label.SetFillStyle(0)
label.SetBorderSize(0)
label.SetTextSize(0.035)
label.SetTextAlign(12)

##all histos with event selection!
###########################################################
MuS0 = mu.Get('h_muPt_Ch0_S0_DataSingleMu')
MuS1 = mu.Get('h_muPt_Ch0_S1_DataSingleMu')
MuS2 = mu.Get('h_muPt_Ch0_S2_DataSingleMu')
MuS0.GetXaxis().SetRangeUser(20,80)
MuS1.GetXaxis().SetRangeUser(20,80)
MuS2.GetXaxis().SetRangeUser(20,80)
MuS0.SetTitle('')
MuS1.SetTitle('')
MuS2.SetTitle('')
MuS0.GetYaxis().SetTitle("Events")
MuS0.SetFillStyle(3004)
MuS0.SetFillColor(1)
MuS1.SetFillStyle(3005)
MuS1.SetFillColor(4)
MuS2.SetFillStyle(3007)
MuS2.SetFillColor(2)
MuS0.Draw('hist')
MuS1.Draw('hist same')
MuS2.Draw('hist same')
l1 = TLegend(0.6, 0.76, 0.85, 0.86)
l1.AddEntry(MuS0, 'p_{T} > 24 GeV', 'F')
l1.AddEntry(MuS1, 'p_{T} > 27 GeV', 'F')
l1.AddEntry(MuS2, 'p_{T} > 30 GeV', 'F')
l1.Draw('SAME')
label.Draw('same')
c1.Print('pt_data_muon.pdf')
c1.Clear()

ElS0 = el.Get('h_elPt_Ch1_S0_DataSingleEG')
ElS1 = el.Get('h_elPt_Ch1_S1_DataSingleEG')
ElS2 = el.Get('h_elPt_Ch1_S2_DataSingleEG')
ElS0.GetXaxis().SetRangeUser(20,80)
ElS1.GetXaxis().SetRangeUser(20,80)
ElS2.GetXaxis().SetRangeUser(20,80)
ElS0.SetTitle('')
ElS1.SetTitle('')
ElS2.SetTitle('')
ElS0.GetYaxis().SetTitle("Events")
ElS0.GetYaxis().SetTitle("Events")
ElS0.SetFillStyle(3004)
ElS0.SetFillColor(1)
ElS1.SetFillStyle(3005)
ElS1.SetFillColor(4)
ElS2.SetFillStyle(3007)
ElS2.SetFillColor(2)
ElS0.Draw('hist')
ElS1.Draw('hist same')
ElS2.Draw('hist same')
l2 = TLegend(0.6, 0.76, 0.85, 0.86)
l2.AddEntry(ElS0, 'p_{T} > 32 GeV', 'F')
l2.AddEntry(ElS1, 'p_{T} > 35 GeV', 'F')
l2.AddEntry(ElS2, 'p_{T} > 38 GeV', 'F')
l2.Draw('SAME')
label.Draw('same')
c1.Print('pt_data_elec.pdf')

MuS0c = tch.Get('h_muPt_Ch0_S0_Top_Hct')
MuS1c = tch.Get('h_muPt_Ch0_S1_Top_Hct')
MuS2c = tch.Get('h_muPt_Ch0_S2_Top_Hct')
MuS0ac = atch.Get('h_muPt_Ch0_S0_AntiTop_Hct')
MuS1ac = atch.Get('h_muPt_Ch0_S1_AntiTop_Hct')
MuS2ac = atch.Get('h_muPt_Ch0_S2_AntiTop_Hct')
MuS0c.Add(MuS0ac,1.0)
MuS1c.Add(MuS1ac,1.0)
MuS2c.Add(MuS2ac,1.0)
MuS0c.GetXaxis().SetRangeUser(20,100)
MuS1c.GetXaxis().SetRangeUser(20,100)
MuS2c.GetXaxis().SetRangeUser(20,100)
MuS0c.SetTitle('')
MuS1c.SetTitle('')
MuS2c.SetTitle('')
MuS0c.GetYaxis().SetTitle("Events")
MuS0c.SetFillStyle(3004)
MuS0c.SetFillColor(1)
MuS1c.SetFillStyle(3005)
MuS1c.SetFillColor(4)
MuS2c.SetFillStyle(3007)
MuS2c.SetFillColor(2)
MuS0c.Draw('hist')
MuS1c.Draw('hist same')
MuS2c.Draw('hist same')
l3 = TLegend(0.6, 0.76, 0.85, 0.86)
l3.AddEntry(MuS0c, 'p_{T} > 24 GeV', 'F')
l3.AddEntry(MuS1c, 'p_{T} > 27 GeV', 'F')
l3.AddEntry(MuS2c, 'p_{T} > 30 GeV', 'F')
l3.Draw('SAME')
label.Draw('same')
c1.Print('pt_hct_muon.pdf')
c1.Clear()

ElS0c = tch.Get('h_elPt_Ch1_S0_Top_Hct')
ElS1c = tch.Get('h_elPt_Ch1_S1_Top_Hct')
ElS2c = tch.Get('h_elPt_Ch1_S2_Top_Hct')
ElS0ac = atch.Get('h_elPt_Ch1_S0_AntiTop_Hct')
ElS1ac = atch.Get('h_elPt_Ch1_S1_AntiTop_Hct')
ElS2ac = atch.Get('h_elPt_Ch1_S2_AntiTop_Hct')
ElS0c.Add(ElS0ac,1.0)
ElS1c.Add(ElS1ac,1.0)
ElS2c.Add(ElS2ac,1.0)
ElS0c.GetXaxis().SetRangeUser(20,100)
ElS1c.GetXaxis().SetRangeUser(20,100)
ElS2c.GetXaxis().SetRangeUser(20,100)
ElS0c.SetTitle('')
ElS1c.SetTitle('')
ElS2c.SetTitle('')
ElS0c.GetYaxis().SetTitle("Events")
ElS0c.SetFillStyle(3004)
ElS0c.SetFillColor(1)
ElS1c.SetFillStyle(3005)
ElS1c.SetFillColor(4)
ElS2c.SetFillStyle(3007)
ElS2c.SetFillColor(2)
ElS0c.Draw('hist')
ElS1c.Draw('hist same')
ElS2c.Draw('hist same')
l3 = TLegend(0.6, 0.76, 0.85, 0.86)
l3.AddEntry(MuS0c, 'p_{T} > 32 GeV', 'F')
l3.AddEntry(MuS1c, 'p_{T} > 35 GeV', 'F')
l3.AddEntry(MuS2c, 'p_{T} > 38 GeV', 'F')
l3.Draw('SAME')
label.Draw('same')
c1.Print('pt_hct_elec.pdf')
c1.Clear()
