cat ../../commonTools/file_top.txt | xargs -i -P$(nproc) -n2 python run_top.py STFCNC
cat ../../commonTools/file_other.txt | xargs -i -P$(nproc) -n2 python run_other.py STFCNC
cat ../../commonTools/file_top.txt | xargs -i -P$(nproc) -n2 python run_top.py STFCNCjecup
cat ../../commonTools/file_other.txt | xargs -i -P$(nproc) -n2 python run_other.py STFCNCjecup
cat ../../commonTools/file_top.txt | xargs -i -P$(nproc) -n2 python run_top.py STFCNCjecdown
cat ../../commonTools/file_other.txt | xargs -i -P$(nproc) -n2 python run_other.py STFCNCjecdown
cat ../../commonTools/file_top.txt | xargs -i -P$(nproc) -n2 python run_top.py STFCNCjerup
cat ../../commonTools/file_other.txt | xargs -i -P$(nproc) -n2 python run_other.py STFCNCjerup
cat ../../commonTools/file_top.txt | xargs -i -P$(nproc) -n2 python run_top.py STFCNCjerdown
cat ../../commonTools/file_other.txt | xargs -i -P$(nproc) -n2 python run_other.py STFCNCjerdown
cat ../../commonTools/file_top.txt | xargs -i -P$(nproc) -n2 python run_top.py TTFCNC
cat ../../commonTools/file_other.txt | xargs -i -P$(nproc) -n2 python run_other.py TTFCNC
cat ../../commonTools/file_top.txt | xargs -i -P$(nproc) -n2 python run_top.py TTFCNCjecup
cat ../../commonTools/file_other.txt | xargs -i -P$(nproc) -n2 python run_other.py TTFCNCjecup
cat ../../commonTools/file_top.txt | xargs -i -P$(nproc) -n2 python run_top.py TTFCNCjecdown
cat ../../commonTools/file_other.txt | xargs -i -P$(nproc) -n2 python run_other.py TTFCNCjecdown
cat ../../commonTools/file_top.txt | xargs -i -P$(nproc) -n2 python run_top.py TTFCNCjerup
cat ../../commonTools/file_other.txt | xargs -i -P$(nproc) -n2 python run_other.py TTFCNCjerup
cat ../../commonTools/file_top.txt | xargs -i -P$(nproc) -n2 python run_top.py TTFCNCjerdown
cat ../../commonTools/file_other.txt | xargs -i -P$(nproc) -n2 python run_other.py TTFCNCjerdown
cat ../../commonTools/file_top.txt | xargs -i -P$(nproc) -n2 python run_top.py TTBKG
cat ../../commonTools/file_other.txt | xargs -i -P$(nproc) -n2 python run_other.py TTBKG
cat ../../commonTools/file_top.txt | xargs -i -P$(nproc) -n2 python run_top.py TTBKGjecup
cat ../../commonTools/file_other.txt | xargs -i -P$(nproc) -n2 python run_other.py TTBKGjecup
cat ../../commonTools/file_top.txt | xargs -i -P$(nproc) -n2 python run_top.py TTBKGjecdown
cat ../../commonTools/file_other.txt | xargs -i -P$(nproc) -n2 python run_other.py TTBKGjecdown
cat ../../commonTools/file_top.txt | xargs -i -P$(nproc) -n2 python run_top.py TTBKGjerup
cat ../../commonTools/file_other.txt | xargs -i -P$(nproc) -n2 python run_other.py TTBKGjerup
cat ../../commonTools/file_top.txt | xargs -i -P$(nproc) -n2 python run_top.py TTBKGjerdown
cat ../../commonTools/file_other.txt | xargs -i -P$(nproc) -n2 python run_other.py TTBKGjerdown
