cat ../../commonTools/file_top.txt | xargs -i -P$(nproc) -n2 python run_top.py STFCNC 2018
cat ../../commonTools/file_syst.txt | xargs -i -P$(nproc) -n2 python run_top.py STFCNC 2018
cat ../../commonTools/file_other.txt | xargs -i -P$(nproc) -n2 python run_other.py STFCNC 2018
cat ../../commonTools/file_top.txt | xargs -i -P$(nproc) -n2 python run_top.py TTFCNC 2018
cat ../../commonTools/file_syst.txt | xargs -i -P$(nproc) -n2 python run_top.py TTFCNC 2018
cat ../../commonTools/file_other.txt | xargs -i -P$(nproc) -n2 python run_other.py TTFCNC 2018
cat ../../commonTools/file_top.txt | xargs -i -P$(nproc) -n2 python run_top.py TTBKG 2018
cat ../../commonTools/file_syst.txt | xargs -i -P$(nproc) -n2 python run_top.py TTBKG 2018
cat ../../commonTools/file_other.txt | xargs -i -P$(nproc) -n2 python run_other.py TTBKG 2018
