#cat ../../commonTools/file_2017_top.txt | xargs -i -P$(nproc) -n2 python run_top.py STFCNC 2017
#cat ../../commonTools/file_2017_syst.txt | xargs -i -P$(nproc) -n2 python run_top.py STFCNC 2017
#cat ../../commonTools/file_2017_other.txt | xargs -i -P$(nproc) -n2 python run_other.py STFCNC 2017
#cat ../../commonTools/file_2017_top.txt | xargs -i -P$(nproc) -n2 python run_top.py TTFCNC 2017
#cat ../../commonTools/file_2017_syst.txt | xargs -i -P$(nproc) -n2 python run_top.py TTFCNC 2017
#cat ../../commonTools/file_2017_other.txt | xargs -i -P$(nproc) -n2 python run_other.py TTFCNC 2017
#cat ../../commonTools/file_2017_top.txt | xargs -i -P$(nproc) -n2 python run_top.py TTBKG 2017
#cat ../../commonTools/file_2017_syst.txt | xargs -i -P$(nproc) -n2 python run_top.py TTBKG 2017
#cat ../../commonTools/file_2017_other.txt | xargs -i -P$(nproc) -n2 python run_other.py TTBKG 2017
cat ../../commonTools/file_2018_top.txt | xargs -i -P$(nproc) -n2 python run_top.py STFCNC 2018
cat ../../commonTools/file_2018_syst.txt | xargs -i -P$(nproc) -n2 python run_top.py STFCNC 2018
cat ../../commonTools/file_2018_other.txt | xargs -i -P$(nproc) -n2 python run_other.py STFCNC 2018
cat ../../commonTools/file_2018_top.txt | xargs -i -P$(nproc) -n2 python run_top.py TTFCNC 2018
cat ../../commonTools/file_2018_syst.txt | xargs -i -P$(nproc) -n2 python run_top.py TTFCNC 2018
cat ../../commonTools/file_2018_other.txt | xargs -i -P$(nproc) -n2 python run_other.py TTFCNC 2018
cat ../../commonTools/file_2018_top.txt | xargs -i -P$(nproc) -n2 python run_top.py TTBKG 2018
cat ../../commonTools/file_2018_syst.txt | xargs -i -P$(nproc) -n2 python run_top.py TTBKG 2018
cat ../../commonTools/file_2018_other.txt | xargs -i -P$(nproc) -n2 python run_other.py TTBKG 2018
